### ISSUE TITLE
Read Lag over 14 days , show_status says running, pid folder empty

### ISSUE THREAD

**Issue by mark-ellul** [the4thdoctor/pg_chameleon#119] opened 2020-08-18 13:44 UTC
**Describe the bug**
I set up pg_chameleon (pg-chameleon 2.0.14), as per the instructions two weeks ago on Digitalocean, I ran a init_replica which made a perfect copy and ran start_replica. It ran once and never read again, hence I have a read lag of over 14 days

chameleon show_status --source mysql --debug
2020-08-18 13:32:31 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 13:32:31 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 13:32:32 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
  Source id  Source name    Type    Status    Consistent    Read lag          Last read            Replay lag    Last replay
-----------  -------------  ------  --------  ------------  ----------------  -------------------  ------------  -------------------
          1  mysql          mysql   running   Yes           14 days 19:59:37  2020-08-03 17:32:55  00:00:00      2020-08-03 17:32:55

== Schema mappings ==
Origin schema    Destination schema
---------------  --------------------
col              col

== Replica status ==
---------------------  -----
Tables not replicated  0
Tables replicated      121
All tables             121
Last maintenance       N/A
Next maintenance       N/A
Replayed rows          16539
Replayed DDL           0
Skipped rows           0
---------------------  -----

**To Reproduce**
All I did was set up the replica as per instructions, did a init_replica and then a start_replica

As I thought it had crashed I ran stop_replica but the status didn't change (noted below)

**Expected behavior**
I expected the replica to be updated with a read lag close to 0

the source is named mysql, the config default and the log file default_mysql_read.log has similar entries...

2020-08-03 10:44:30 read_replica INFO: Saved master data for source: mysql
.... updating every few seconds until ...
2020-08-03 17:32:55 read_replica INFO: Saved master data for source: mysql

**Environment(please complete the following information):**
 - OS: [e.g. Devuan GNU/Linux]
ubuntu 14.04.1 - source database
ubuntu 20.04.1 LTS replica database
 - MySQL Version[e.g. 5.7.27]
version	5.6.33-0ubuntu0.14.04.1-log

 - PostgreSQL Version[e.g. 11]
psql (12.2 (Ubuntu 12.2-4))

 - Python Version [e.g. 3.5]
Python 3.8.2 

 - Cloud hosted database [e.g PostgreSQL on AWS RDS and MySQL on Google Cloud] 

Postgres ( psql (12.2 (Ubuntu 12.2-4)) ) running on Digital Ocean
MySQL on Digital Ocean

**Additional context**
when I run stop_replica the status doesn't change...

(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon stop_replica --source mysql --debug
2020-08-18 13:33:39 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 13:33:39 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True

(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon show_status --source mysql --debug
2020-08-18 13:34:11 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 13:34:11 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 13:34:11 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
  Source id  Source name    Type    Status    Consistent    Read lag          Last read            Replay lag    Last replay
-----------  -------------  ------  --------  ------------  ----------------  -------------------  ------------  -------------------
          1  mysql          mysql   running   Yes           14 days 20:01:16  2020-08-03 17:32:55  00:00:00      2020-08-03 17:32:55

== Schema mappings ==
Origin schema    Destination schema
---------------  --------------------
col              col

== Replica status ==
---------------------  -----
Tables not replicated  0
Tables replicated      121
All tables             121
Last maintenance       N/A
Next maintenance       N/A
Replayed rows          16539
Replayed DDL           0
Skipped rows           0
---------------------  -----

Any help would be very much appreciated

**Comment by mark-ellul** [comment] 2020-08-18 15:22
now after running enable_replica the status is stopped and I have another error,which I will put in a different ticket

**Comment by mark-ellul** [comment] 2020-08-31 09:08
Hi, 

I am hitting this issue again, I have a read lag of over 5 days now.

Any help in investigating would be appreciated!

Regards

Mark

**Comment by the4thdoctor** [comment] 2020-09-01 03:59
if the pid folder is empty something has gone wrong. I'd run `chameleon start_replica --source mysql --debug` and check for any crash message in the log.

**Comment by mark-ellul** [comment] 2020-09-01 11:45
```(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon start_replica --config default --source mysql --debug
2020-09-01 05:46:57 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:46:57 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:46:57 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:46:57 MainProcess INFO global_lib.py (608): Checking if the replica for source mysql is stopped 
The replica process is already started or is syncing. Aborting the command.
```

It doesn't start again!

So I tried these commands, and it doesn't "stop" either...

```
(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon show_errors --config default --source mysql --debug
2020-09-01 05:48:56 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:48:56 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:48:56 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
There are no errors in the log
(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon stop_replica --config default --source mysql --debug
2020-09-01 05:49:24 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:49:24 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon show_status --config default --source mysql --debug
2020-09-01 05:49:47 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:49:47 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:49:47 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
  Source id  Source name    Type    Status    Consistent    Read lag         Last read            Replay lag    Last replay
-----------  -------------  ------  --------  ------------  ---------------  -------------------  ------------  -------------------
          1  mysql          mysql   running   Yes           5 days 23:18:40  2020-08-26 06:31:07  00:00:00      2020-08-26 06:31:07

== Schema mappings ==
Origin schema    Destination schema
---------------  --------------------
col              col

== Replica status ==
---------------------  -----
Tables not replicated  0
Tables replicated      121
All tables             121
Last maintenance       N/A
Next maintenance       N/A
Replayed rows          11253
Replayed DDL           0
Skipped rows           0
---------------------  -----
(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon show_status --config default --source mysql --debug
2020-09-01 05:50:56 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:50:56 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:50:56 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
  Source id  Source name    Type    Status    Consistent    Read lag         Last read            Replay lag    Last replay
-----------  -------------  ------  --------  ------------  ---------------  -------------------  ------------  -------------------
          1  mysql          mysql   running   Yes           5 days 23:19:49  2020-08-26 06:31:07  00:00:00      2020-08-26 06:31:07

== Schema mappings ==
Origin schema    Destination schema
---------------  --------------------
col              col

== Replica status ==
---------------------  -----
Tables not replicated  0
Tables replicated      121
All tables             121
Last maintenance       N/A
Next maintenance       N/A
Replayed rows          11253
Replayed DDL           0
Skipped rows           0
---------------------  -----
```

I ended up running the enable_replica command and then the start_replica and it seems to have started again

```
2020-09-01 05:59:24 read_replica DEBUG pg_lib.py (3321): Checking consistent status for source: mysql
2020-09-01 05:59:24 read_replica DEBUG pg_lib.py (3354): The source: mysql is consistent
2020-09-01 05:59:24 MainProcess DEBUG global_lib.py (558): Replica process for source mysql is running
2020-09-01 05:59:24 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:59:24 MainProcess DEBUG pg_lib.py (1276): Cleaning replayed batches for source mysql older than 20 day
2020-09-01 05:59:25 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-09-01 05:59:25 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-09-01 05:59:25 read_replica DEBUG pg_lib.py (3110): Collecting schema mappings for source mysql
2020-09-01 05:59:25 read_replica DEBUG mysql_lib.py (1411): Batch data [(45670, 'mysql-bin.000050', 20961878, 't_log_replica_mysql_1', '')] 
2020-09-01 05:59:25 read_replica DEBUG mysql_lib.py (959): collecting table type map
2020-09-01 05:59:25 read_replica DEBUG mysql_lib.py (1176): GTID DISABLED - log_file mysql-bin.000050, log_position 20961878. id_batch: 45670 
2020-09-01 05:59:25 read_replica DEBUG mysql_lib.py (1190): ROTATE EVENT - binlogfile mysql-bin.000050, position 20961878. 
2020-09-01 05:59:25 read_replica DEBUG pg_lib.py (3321): Checking consistent status for source: mysql
2020-09-01 05:59:25 read_replica DEBUG pg_lib.py (3354): The source: mysql is consistent
2020-09-01 05:59:25 MainProcess DEBUG global_lib.py (558): Replica process for source mysql is running
2020-09-01 05:59:25 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:59:25 MainProcess DEBUG pg_lib.py (1276): Cleaning replayed batches for source mysql older than 20 day
2020-09-01 05:59:26 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-09-01 05:59:26 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-09-01 05:59:26 read_replica DEBUG pg_lib.py (3110): Collecting schema mappings for source mysql
2020-09-01 05:59:26 read_replica DEBUG mysql_lib.py (1411): Batch data [(45670, 'mysql-bin.000050', 20961878, 't_log_replica_mysql_1', '')] 
2020-09-01 05:59:26 read_replica DEBUG mysql_lib.py (959): collecting table type map
2020-09-01 05:59:26 read_replica DEBUG mysql_lib.py (1176): GTID DISABLED - log_file mysql-bin.000050, log_position 20961878. id_batch: 45670 
2020-09-01 05:59:26 read_replica DEBUG mysql_lib.py (1190): ROTATE EVENT - binlogfile mysql-bin.000050, position 20961878. 
2020-09-01 05:59:26 read_replica DEBUG pg_lib.py (3321): Checking consistent status for source: mysql
2020-09-01 05:59:26 read_replica DEBUG pg_lib.py (3354): The source: mysql is consistent
2020-09-01 05:59:26 MainProcess DEBUG global_lib.py (558): Replica process for source mysql is running
2020-09-01 05:59:26 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-09-01 05:59:26 MainProcess DEBUG pg_lib.py (1276): Cleaning replayed batches for source mysql older than 20 day
2020-09-01 05:59:27 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-09-01 05:59:27 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-09-01 05:59:27 read_replica DEBUG pg_lib.py (3110): Collecting schema mappings for source mysql
2020-09-01 05:59:27 read_replica DEBUG mysql_lib.py (1411): Batch data [(45670, 'mysql-bin.000050', 20961878, 't_log_replica_mysql_1', '')] 
2020-09-01 05:59:27 read_replica DEBUG mysql_lib.py (959): collecting table type map
2020-09-01 05:59:27 read_replica DEBUG mysql_lib.py (1176): GTID DISABLED - log_file mysql-bin.000050, log_position 20961878. id_batch: 45670 
2020-09-01 05:59:27 read_replica DEBUG mysql_lib.py (1190): ROTATE EVENT - binlogfile mysql-bin.000050, position 20961878. 
2020-09-01 05:59:27 read_replica DEBUG pg_lib.py (3321): Checking consistent status for source: mysql
2020-09-01 05:59:
```

**Comment by the4thdoctor** [comment] 2020-09-02 05:58
Yes, I was suggesting to use `enable_replica`.
I need to add a crash dump report for the daemonised process. It may be very useful for understading what's wrong in case of crash.

**Comment by mark-ellul** [comment] 2020-09-02 12:22
When you add the crash dump report for the daemonised process let me know and I will deploy it to see. The process has been running for a couple of days without any issues so far!

**Comment by the4thdoctor** [comment] 2022-02-15 20:27
I'm closing this issue as it seems the problem is no longer there.

**Closed by the4thdoctor** 2022-02-15 20:27 UTC
