### ISSUE TITLE
a very strange error log

### ISSUE THREAD

**Issue by lingniao2000** [the4thdoctor/pg_chameleon#60] opened 2018-01-16 09:09 UTC
hi I'll report a problem again
We are in the process of importing single-table data, there is a very strange error log. But we checked the table in the postgreSQL is consistent. We tried to add the logs and did the analysis, but there was no conclusion, please help me

In addition to the chaotic character encoding problems, such as ^ M (unquoted carriage return found in data), invalid byte sequence for encoding "UTF8": 0x00, hoping to add more detailed log, we need to know very well which lines were skiped
command:

chameleon.py sync_tables --source prod --tables db_nono.user_info --debug

2018-01-16 16:46:09 MainProcess DEBUG pg_lib.py (608): Changing the autocommit flag to False
2018-01-16 16:46:09 MainProcess INFO pg_lib.py (3124): Swapping table db_nono.user_info with _db_nono_tmp.user_info
2018-01-16 16:46:09 MainProcess DEBUG pg_lib.py (3127): Dropping the original table db_nono.user_info
2018-01-16 16:46:09 MainProcess DEBUG pg_lib.py (3129): Changing the schema for table _db_nono_tmp.user_info to db_nono
2018-01-16 16:46:10 MainProcess DEBUG pg_lib.py (608): Changing the autocommit flag to True
2018-01-16 16:46:10 MainProcess DEBUG mysql_lib.py (246): Dropping the schema _db_nono_tmp.
2018-01-16 16:46:10 MainProcess DEBUG pg_lib.py (646): Changing the lock timeout for the session to 600s.
2018-01-16 16:46:10 MainProcess INFO pg_lib.py (2800): Set high watermark for source: prod
2018-01-16 16:46:10 MainProcess ERROR global_lib.py (55): Could not send the message to rollbar.
2018-01-16 16:46:10 MainProcess INFO mysql_lib.py (809): the sync for tables db_nono.user_info in source prod is complete
/root/.pyenv/versions/3.5.3/envs/chameleon/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py:649: Warning: (1292, "Incorrect datetime value
: '0000-00-00 00:00:00' for column 'register_time' at row 1 ")
  master_status = self.copy_data (schema, table)
/root/.pyenv/versions/3.5.3/envs/chameleon/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py:649: Warning: (1292, "Incorrect datetime value
: '0000-00-00 00:00:00' for column 'create_time' at row 1 ")
  master_status = self.copy_data (schema, table)
/root/.pyenv/versions/3.5.3/envs/chameleon/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py:649: Warning: (1292, "Incorrect datetime value
: '0000-00-00 00:00:00' for column 'update_time' at row 1 ")
  master_status = self.copy_data (schema, table)

**Comment by the4thdoctor** [comment] 2018-01-16 09:37
that's interesting. I remember I solved this issue with the request #16 
probably I missed that part when writing the new version :(

**Comment by lingniao2000** [comment] 2018-01-16 09:52
Thanks for getting your feedback so fast
On the MySQL side, I've updated the fields containing NULL or '0000-00-00 00:00:00', and there are special characters garbled, I also updated, I do not know why this error still occurs

**Comment by the4thdoctor** [comment] 2018-01-16 14:00
can you provide me an example data set?

**Comment by the4thdoctor** [comment] 2018-01-16 20:40
hi, I've run some tests against a mysql 5.7 database and the warning is issued.
however the rows are correctly stored as NULL which is the same behavior of the mysql replication library.
can you please check if the rows are present?
I suspect the warning it's just a warning issued by the pymysql driver rather a real problem.

thanks

**Comment by lingniao2000** [comment] 2018-01-17 01:15
oh！ sorry, The above post is wrong. I mean:
found a strange error log. But we checked the data in the postgreSQL table is indeed consistent

**Comment by the4thdoctor** [comment] 2018-01-17 07:16
cool, I'm closing the issue as not a bug then.
thanks for your feedback

**Comment by lingniao2000** [comment] 2018-01-17 09:01
Got some information

STR_TO_DATE(str,format)
This is the inverse of the DATE_FORMAT() function. It takes a string str and a format string format. STR_TO_DATE() returns a DATETIME value if the format string contains both date and time parts, or a DATE or TIME value if the string contains only date or time parts. If the date, time, or datetime value extracted from str is illegal, **STR_TO_DATE() returns NULL and produces a warning.**

    def _nextset(self, unbuffered=False):
        """Get the next query set"""
        conn = self._get_db()
        current_result = self._result
        **# for unbuffered queries warnings are only available once whole result has been read**
        if unbuffered:
            self._show_warnings()
        if current_result is None or current_result is not conn._result:
            return None
        if not current_result.has_next:
            return None
        conn.next_result(unbuffered=unbuffered)
        self._do_get_result()
        return True

**Comment by the4thdoctor** [comment] 2018-01-17 09:26
so, definitely is a driver's warning. 
Thanks for the information :)

**Closed** 2018-01-17 09:26 UTC
Labels: not a bug, v2.0, v2.1
