### ISSUE TITLE
read phase delay still too high

### ISSUE THREAD

**Issue by lingniao2000** [the4thdoctor/pg_chameleon#62] opened 2018-01-25 02:03 UTC
hi , i am come back again

Once again, I import the data for testing with the latest v2.0.2 version, and it still takes a very long time to reach a consistent state, which takes about two days. I analyzed it, and it looks like the read_lag phase has a very high latency, not a replay phase. [# 59](https://github.com/the4thdoctor/pg_chameleon/issues/59) solve the same problem?
	
	[2018-01-24_09: 36: 36] Source id Source name Type Status Consistent Read lag Last read Replay lag Last replay
	[2018-01-24_09: 36: 36] ----------- ------------- ------ -------- - ----------- ---------- ------------------- ---------- - -------------------
	[2018-01-24_09: 36: 36] 1 prod mysql running Yes 08:18:26 2018-01-24 01:18:09 00:00:00 2018-01-24 01:18:09
	[2018-01-24_09: 36: 36]
	[2018-01-24_09: 36: 36] == Schema mappings ==
	[2018-01-24_09: 36: 36] Origin schema Destination schema
	[2018-01-24_09: 36: 36] --------------- --------------------
	[2018-01-24_09: 36: 36] db_nono db_nono
	[2018-01-24_09: 36: 36]
	[2018-01-24_09: 36: 36] == Replica status ==
	[2018-01-24_09: 36: 36] --------------------- -----------
	[2018-01-24_09: 36: 36] Tables not replicated 0
	[2018-01-24_09: 36: 36] Tables replicated 7
	[2018-01-24_09: 36: 36] All tables 7
	[2018-01-24_09: 36: 36] Replayed rows 2.19462e + 07
	[2018-01-24_09: 36: 36] Replayed DDL 0
	[2018-01-24_09: 36: 36] Skipped rows 0

**Comment by the4thdoctor** [comment] 2018-01-25 06:12
Hi, the read and replay are two distinct functions and #59 should solve only the replay part.
What I suggest you is to tune the two parameters ``replica_batch_size:`` and  ``replay_max_rows:``.

For what I've found, a large ``replica_batch_size``, around 100k rows, performs very well unless there is rubbish in the data stream. On the opposite the ``replay_max_rows`` works best with small values, around 10k.

 I would also check the PostgreSQL configuration.
Can you please post the values of ``shared_buffer``s and ``work_mem`` in your installation please?

**Comment by lingniao2000** [comment] 2018-01-25 06:40
My configuration:
        replica_batch_size: 20000
        replay_max_rows: 10000
postgresql.conf:
[postgresql.conf.txt](https://github.com/the4thdoctor/pg_chameleon/files/1662779/postgresql.conf.txt)

**Comment by the4thdoctor** [comment] 2018-01-25 06:53
I suggest you to increase the replica batch size to 100k.
How much memory on your postgres server? 
A quick check tells me you'll need at least 500GB ram.

**Comment by lingniao2000** [comment] 2018-01-25 07:00
ok  , i will increase the replica_batch_size to 100K and test again
my server physical memory 256GB and SSD disk

**Comment by the4thdoctor** [comment] 2018-01-25 07:10
Well. I suggest you to lower the shared buffer to 3gb and increase the work memory to 50mb

**Comment by lingniao2000** [comment] 2018-01-25 07:38
I am confused
lower shared_buffers to 3GB, postgreSQL will not be slower?
work_mem = 1024MB allready bigger than 50MB !

**Comment by the4thdoctor** [comment] 2018-01-25 09:17
sorry. I'm still sleeping :)
basically the a smaller shared buffer will not affect too much the performance as postgres caching is very effective. on the other side increasing the work mem will reduce the need for swapping on disk  during the sorts required by the replay replica. 
as you have 256 GB I won't risk more than 5 GB of  shared buffer and 500MB work mem which is per user and has to be multiplied by the number of max connections.

5 GB +  (0.5 GB * 400) = 205 GB (better reduce the total memory by 10% as there are other processes on the OS).

if you are expecting less clients you can a reduce the max_connections and recalculate the memory requirements.
I'd also increase the checkpoint completion target to 0.9 as the lower value you've set will lead to io spikes.

**Comment by lingniao2000** [comment] 2018-01-25 09:43
read_lag delay is high, is it possible because of the low efficiency of BinLogStreamReader?
Maybe this time, binlog data has not been obtained

**Comment by the4thdoctor** [comment] 2018-01-25 09:45
well the read lag is not very accurate (see caveats in the README).
if the tables are mostly static the value will increase because no more events are received from the database.

**Comment by lingniao2000** [comment] 2018-01-25 10:05
My situation is not the case, our data is real-time changes, and I have carefully compared the time in MySQL and PostgreSQL compared to the data, there is really a high delay

**Comment by the4thdoctor** [comment] 2018-01-25 18:28
I suggest you to reduce the size of the binog files on MySQL.
500 MB can generate very large batches which slow down the replay. 100MB should be much better.

 I suggest also to use pgbadger  https://github.com/dalibo/pgbadger or a monitoring system like https://www.cybertec-postgresql.com/en/products/pgwatch2/ in order to determine where is the bottleneck on PostgreSQL.

**Comment by lingniao2000** [comment] 2018-01-28 02:33
I changed a new machine, installed pg_chameleon and postgreSQL to do the test, found slow read phase evidence, repay a batch only takes 5 seconds, and switch a binlog, it takes 15 minutes

	2018-01-28 09:55:18 read_replica DEBUG mysql_lib.py (940): ROTATE EVENT - binlogfile mysql-bin.004524, position 4
	2018-01-28 09:55:27 read_replica DEBUG mysql_lib.py (933): log_file mysql-bin.004524, log_position 4. id_batch: 3
	2018-01-28 10:00:26 read_replica INFO mysql_lib.py (1086): Max rows per batch reached. Writing 100000. rows. Size in bytes: 82468472
	2018-01-28 10:00:26 read_replica DEBUG mysql_lib.py (1087): Master coordinates: {'Position': 162954940, 'File': 'mysql-bin.004524', 'Time': 1517057123}
	
	2018-01-28 10:00:49 read_replica DEBUG mysql_lib.py (933): log_file mysql-bin.004524, log_position 162954940. id_batch: 4
	2018-01-28 10:00:49 read_replica DEBUG mysql_lib.py (940): ROTATE EVENT - binlogfile mysql-bin.004524, position 162954940
	2018-01-28 10:00:57 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:10 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:22 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:28 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:32 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:37 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:43 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:48 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:53 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:01:58 replay_replica INFO pg_lib.py (854): Replayed at most 10000 rows for source prod
	2018-01-28 10:06:26 read_replica INFO mysql_lib.py (1086): Max rows per batch reached. Writing 100000. rows. Size in bytes: 82844977
	
	2018-01-28 10:06:49 read_replica DEBUG mysql_lib.py (933): log_file mysql-bin.004524, log_position 346162481. id_batch: 5
	2018-01-28 10:06:49 read_replica DEBUG mysql_lib.py (940): ROTATE EVENT - binlogfile mysql-bin.004524, position 346162481.
	
	2018-01-28 10:11:37 read_replica DEBUG mysql_lib.py (940): ROTATE EVENT - binlogfile mysql-bin.004525, position 4.

**Comment by lingniao2000** [comment] 2018-01-28 02:35
[default_prod.txt](https://github.com/the4thdoctor/pg_chameleon/files/1670726/default_prod.txt)

**Comment by lingniao2000** [comment] 2018-01-28 02:49
**pg_chameleon read process pid 52306**
**Recv-Q is high**
	[root@QH-PRD-STGE-MYSQL-MHA08 chameleon]# netstat -natlp
	Active Internet connections (servers and established)
	Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
	tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1200/sshd           
	tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      47875/postmaster    
	tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2086/master         
	tcp        0      0 172.20.20.27:5432       192.168.46.11:64869     ESTABLISHED 52356/postgres: pos 
	tcp        0      0 172.20.20.27:5432       192.168.46.11:64824     ESTABLISHED 52278/postgres: pos 
	tcp        0      0 172.30.0.27:46607       172.30.0.13:3306        ESTABLISHED 52306/python3.5     
	tcp        0      0 172.20.20.27:41121      172.16.30.204:3306      ESTABLISHED 24904/mysqld        
	tcp        0      0 172.30.0.27:54365       172.30.0.27:5432        ESTABLISHED 52306/python3.5     
	tcp        0    240 172.20.20.27:22         192.168.46.11:64763     ESTABLISHED 52208/sshd: root@pt 
	tcp        0      0 172.30.0.27:5432        172.30.0.27:54363       ESTABLISHED 52308/postgres: pos 
	tcp        0      0 172.20.20.27:5432       192.168.46.11:64823     ESTABLISHED 52276/postgres: pos 
	tcp        0      0 172.30.0.27:5432        172.30.0.27:54365       ESTABLISHED 52309/postgres: pos 
	tcp   223072      0 172.30.0.27:46605       172.30.0.13:3306        ESTABLISHED 52306/python3.5

**strace output** 
	(chameleon)[root@QH-PRD-STGE-MYSQL-MHA08 pg_chameleon]# strace -c -p 52306
	strace: Process 52306 attached
	^Cstrace: Process 52306 detached
	% time     seconds  usecs/call     calls    errors syscall
	------ ----------- ----------- --------- --------- ----------------
	 92.48    0.055257           0   1087063           ioctl
	  7.33    0.004382           0     10156           recvfrom
	  0.19    0.000112           0       442           stat
	  0.00    0.000000           0         1           sendto
	------ ----------- ----------- --------- --------- ----------------
	100.00    0.059751               1097662           total

**Comment by the4thdoctor** [comment] 2018-01-28 06:12
Interesting. Which version of mysql are you using?
I need to try to reproduce the issue

**Comment by lingniao2000** [comment] 2018-01-28 09:51
mysql version 5.7.17-log

Federico Campoli <notifications@github.com>于2018年1月28日 周日14:12写道：

**Comment by the4thdoctor** [comment] 2018-01-28 10:05
can you upgrade it to the version 5.7.21? https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-21.html 

Just to be sure you are not hitting a situation similar to #47 

Thanks

**Comment by lingniao2000** [comment] 2018-01-28 13:01
I am changing to mysql version 5.6.37-82.2 and test again

**Comment by lingniao2000** [comment] 2018-01-29 02:07
Again test, the problem is still the same, binlog switch takes 15 minutes, MySQL we are using a PCI-E SSD, postgreSQL iostat command to view the server IO pressure is very light

**Comment by the4thdoctor** [comment] 2018-01-30 10:33
sorr y for the delay. I had no time for looking to the problem.
possibly I'll be able to check over the week end.

**Comment by lingniao2000** [comment] 2018-02-11 07:27
2018-02-11 11:50:22 read_replica DEBUG mysql_lib.py (1087): Master coordinates: {'File': 'mysql-bin.000954', 'Time': 1518298040, 'Position': 499994791}
	Timer unit: 1e-06 s
	
	Total time: 628.137 s
	File: /root/chameleon/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py
	Function: __read_replica_stream at line 881
	
	Line #      Hits         Time  Per Hit   % Time  Line Contents
	==============================================================
	   881                                           	def __read_replica_stream(self, batch_data):
	   882                                           		"""
	   883                                           		Stream the replica using the batch data. This method evaluates the different events streamed from MySQL 
	   884                                           		and manages them accordingly. The BinLogStreamReader function is called with the only_event parameter which
	   885                                           		restricts the event type received by the streamer.
	   886                                           		The events managed are the following.
	   887                                           		RotateEvent which happens whether mysql restarts or the binary log file changes.
	   888                                           		QueryEvent which happens when a new row image comes in (BEGIN statement) or a DDL is executed.
	   889                                           		The BEGIN is always skipped. The DDL is parsed using the sql_token class. 
	   890                                           		[Write,Update,Delete]RowEvents are the row images pulled from the mysql replica.
	   891                                           		
	   892                                           		The RotateEvent and the QueryEvent cause the batch to be closed.
	   893                                           		
	   894                                           		The for loop reads the row events, builds the dictionary carrying informations like the destination schema,
	   895                                           		the 	binlog coordinates and store them into the group_insert list.
	   896                                           		When the number of events exceeds the replica_batch_size the group_insert is written into PostgreSQL.
	   897                                           		The batch is not closed in that case and the method exits only if there are no more rows available in the stream.
	   898                                           		Therefore the replica_batch_size is just the maximum size of the single insert and the size of replayed batch on PostgreSQL.
	   899                                           		The binlog switch or a captured DDL determines whether a batch is closed and processed.
	   900                                           		
	   901                                           		The update row event stores in a separate key event_before the row image before the update. This is required
	   902                                           		to allow updates where the primary key is updated as well.
	   903                                           		
	   904                                           		Each row event is scanned for data types requiring conversion to hex string.
	   905                                           		
	   906                                           		:param batch_data: The list with the master's batch data.
	   907                                           		:return: the batch's data composed by binlog name, binlog position and last event timestamp read from the mysql replica stream.
	   908                                           		:rtype: dictionary
	   909                                           		"""
	   910         1          9.0      9.0      0.0  		size_insert=0
	   911         1      62448.0  62448.0      0.0  		sql_tokeniser = sql_token()
	   912         1    1866884.0 1866884.0      0.3  		table_type_map = self.get_table_type_map()	
	   913         1       1162.0   1162.0      0.0  		inc_tables = self.pg_engine.get_inconsistent_tables()
	   914         1          4.0      4.0      0.0  		close_batch = False
	   915         1          5.0      5.0      0.0  		master_data = {}
	   916         1          3.0      3.0      0.0  		group_insert = []
	   917                                           		
	   918         1          5.0      5.0      0.0  		id_batch = batch_data[0][0]
	   919         1          3.0      3.0      0.0  		log_file = batch_data[0][1]
	   920         1          3.0      3.0      0.0  		log_position = batch_data[0][2]
	   921         1          3.0      3.0      0.0  		log_table = batch_data[0][3]
	   922                                           		
	   923         1         19.0     19.0      0.0  		my_stream = BinLogStreamReader(
	   924         1          4.0      4.0      0.0  			connection_settings = self.replica_conn, 
	   925         1          6.0      6.0      0.0  			server_id = self.my_server_id, 
	   926         1         21.0     21.0      0.0  			only_events = [RotateEvent, DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent, QueryEvent], 
	   927         1          3.0      3.0      0.0  			log_file = log_file, 
	   928         1          2.0      2.0      0.0  			log_pos = log_position, 
	   929         1          3.0      3.0      0.0  			resume_stream = True, 
	   930         1        157.0    157.0      0.0  			only_schemas = self.schema_replica, 
	   931                                           			
	   932                                           		)
	   933         1        420.0    420.0      0.0  		self.logger.debug("log_file %s, log_position %s. id_batch: %s " % (log_file, log_position, id_batch))
	   934                                           		
	   935    225048  210244314.0    934.2     33.5  		for binlogevent in my_stream:
	   936    225048     870337.0      3.9      0.1  			if isinstance(binlogevent, RotateEvent):
	   937         1          2.0      2.0      0.0  				event_time = binlogevent.timestamp
	   938         1          3.0      3.0      0.0  				binlogfile = binlogevent.next_binlog
	   939         1          2.0      2.0      0.0  				position = binlogevent.position
	   940         1        305.0    305.0      0.0  				self.logger.debug("ROTATE EVENT - binlogfile %s, position %s. " % (binlogfile, position))
	   941         1          3.0      3.0      0.0  				if log_file != binlogfile:
	   942                                           					close_batch = True
	   943         1          2.0      2.0      0.0  				if close_batch:
	   944                                           					if log_file!=binlogfile:
	   945                                           						master_data["File"]=binlogfile
	   946                                           						master_data["Position"]=position
	   947                                           						master_data["Time"]=event_time
	   948                                           					if len(group_insert)>0:
	   949                                           						self.pg_engine.write_batch(group_insert)
	   950                                           						group_insert=[]
	   951                                           					my_stream.close()
	   952                                           					return [master_data, close_batch]
	   953    225047     654162.0      2.9      0.1  			elif isinstance(binlogevent, QueryEvent):
	   954    111908     299863.0      2.7      0.0  				event_time = binlogevent.timestamp
	   955    111908     282476.0      2.5      0.0  				try:
	   956    111908     370480.0      3.3      0.1  					schema_query = binlogevent.schema.decode()
	   957                                           				except:
	   958                                           					schema_query = binlogevent.schema
	   959                                           				
	   960    111908     528751.0      4.7      0.1  				if binlogevent.query.strip().upper() not in self.statement_skip and schema_query in self.schema_mappings: 
	   961                                           					close_batch=True
	   962                                           					destination_schema = self.schema_mappings[schema_query]
	   963                                           					log_position = binlogevent.packet.log_pos
	   964                                           					master_data["File"] = binlogfile
	   965                                           					master_data["Position"] = log_position
	   966                                           					master_data["Time"] = event_time
	   967                                           					if len(group_insert)>0:
	   968                                           						self.pg_engine.write_batch(group_insert)
	   969                                           						group_insert=[]
	   970                                           					self.logger.info("QUERY EVENT - binlogfile %s, position %s.\n--------\n%s\n-------- " % (binlogfile, log_position, binlogevent.query))
	   971                                           					sql_tokeniser.parse_sql(binlogevent.query)
	   972                                           					for token in sql_tokeniser.tokenised:
	   973                                           						write_ddl = True
	   974                                           						table_name = token["name"] 
	   975                                           						store_query = self.__store_binlog_event(table_name, schema_query)
	   976                                           						if store_query:
	   977                                           							table_key_dic = "%s.%s" % (destination_schema, table_name)
	   978                                           							if table_key_dic in inc_tables:
	   979                                           								write_ddl = False
	   980                                           								log_seq = int(log_file.split('.')[1])
	   981                                           								log_pos = int(log_position)
	   982                                           								table_dic = inc_tables[table_key_dic]
	   983                                           								if log_seq > table_dic["log_seq"]:
	   984                                           									write_ddl = True
	   985                                           								elif log_seq == table_dic["log_seq"] and log_pos >= table_dic["log_pos"]:
	   986                                           									write_ddl = True
	   987                                           								if write_ddl:
	   988                                           									self.logger.info("CONSISTENT POINT FOR TABLE %s REACHED  - binlogfile %s, position %s" % (table_key_dic, binlogfile, log_position))
	   989                                           									self.pg_engine.set_consistent_table(table_name, destination_schema)
	   990                                           									inc_tables = self.pg_engine.get_inconsistent_tables()
	   991                                           							if write_ddl:
	   992                                           								event_time = binlogevent.timestamp
	   993                                           								self.logger.debug("TOKEN: %s" % (token))
	   994                                           								
	   995                                           								if len(token)>0:
	   996                                           									query_data={
	   997                                           										"binlog":log_file, 
	   998                                           										"logpos":log_position, 
	   999                                           										"schema": destination_schema, 
	  1000                                           										"batch_id":id_batch, 
	  1001                                           										"log_table":log_table
	  1002                                           									}
	  1003                                           									self.pg_engine.write_ddl(token, query_data, destination_schema)
	  1004                                           								
	  1005                                           							
	  1006                                           						
	  1007                                           					sql_tokeniser.reset_lists()
	  1008    111908     327791.0      2.9      0.1  				if close_batch:
	  1009         1       6171.0   6171.0      0.0  					my_stream.close()
	  1010         1         10.0     10.0      0.0  					return [master_data, close_batch]
	  1011                                           			else:
	  1012                                           				
	  1013    226441  301239216.0   1330.3     48.0  				for row in binlogevent.rows:
	  1014    113302     405720.0      3.6      0.1  					event_after={}
	  1015    113302     312578.0      2.8      0.0  					event_before={}
	  1016    113302     307789.0      2.7      0.0  					event_insert = {}
	  1017    113302     291520.0      2.6      0.0  					add_row = True
	  1018    113302     295851.0      2.6      0.0  					log_file=binlogfile
	  1019    113302     333946.0      2.9      0.1  					log_position=binlogevent.packet.log_pos
	  1020    113302     309611.0      2.7      0.0  					table_name=binlogevent.table
	  1021    113302     306875.0      2.7      0.0  					event_time=binlogevent.timestamp
	  1022    113302     309094.0      2.7      0.0  					schema_row = binlogevent.schema
	  1023    113302     374388.0      3.3      0.1  					destination_schema = self.schema_mappings[schema_row]
	  1024    113302     544706.0      4.8      0.1  					table_key_dic = "%s.%s" % (destination_schema, table_name)
	  1025    113302     717104.0      6.3      0.1  					store_row = self.__store_binlog_event(table_name, schema_row)
	  1026    113302     301882.0      2.7      0.0  					if store_row:
	  1027    100000     295039.0      3.0      0.0  						if table_key_dic in inc_tables:
	  1028                                           							table_consistent = False
	  1029                                           							log_seq = int(log_file.split('.')[1])
	  1030                                           							log_pos = int(log_position)
	  1031                                           							table_dic = inc_tables[table_key_dic]
	  1032                                           							if log_seq > table_dic["log_seq"]:
	  1033                                           								table_consistent = True
	  1034                                           							elif log_seq == table_dic["log_seq"] and log_pos >= table_dic["log_pos"]:
	  1035                                           								table_consistent = True
	  1036                                           								self.logger.info("CONSISTENT POINT FOR TABLE %s REACHED  - binlogfile %s, position %s" % (table_key_dic, binlogfile, log_position))
	  1037                                           							if table_consistent:
	  1038                                           								add_row = True
	  1039                                           								self.pg_engine.set_consistent_table(table_name, destination_schema)
	  1040                                           								inc_tables = self.pg_engine.get_inconsistent_tables()
	  1041                                           							else:
	  1042                                           								add_row = False
	  1043                                           						
	  1044    100000     306254.0      3.1      0.0  						column_map=table_type_map[schema_row][table_name]
	  1045                                           						global_data={
	  1046    100000     263268.0      2.6      0.0  											"binlog":log_file, 
	  1047    100000     257251.0      2.6      0.0  											"logpos":log_position, 
	  1048    100000     256362.0      2.6      0.0  											"schema": destination_schema, 
	  1049    100000     256799.0      2.6      0.0  											"table": table_name, 
	  1050    100000     259727.0      2.6      0.0  											"batch_id":id_batch, 
	  1051    100000     258375.0      2.6      0.0  											"log_table":log_table, 
	  1052    100000     377320.0      3.8      0.1  											"event_time":event_time
	  1053                                           										}
	  1054    100000     264899.0      2.6      0.0  						if add_row:
	  1055    100000     395324.0      4.0      0.1  							if isinstance(binlogevent, DeleteRowsEvent):
	  1056                                           								global_data["action"] = "delete"
	  1057                                           								event_after=row["values"]
	  1058    100000     289042.0      2.9      0.0  							elif isinstance(binlogevent, UpdateRowsEvent):
	  1059     99871     282344.0      2.8      0.0  								global_data["action"] = "update"
	  1060     99871     298102.0      3.0      0.0  								event_after=row["after_values"]
	  1061     99871     279297.0      2.8      0.0  								event_before=row["before_values"]
	  1062       129        389.0      3.0      0.0  							elif isinstance(binlogevent, WriteRowsEvent):
	  1063       129        363.0      2.8      0.0  								global_data["action"] = "insert"
	  1064       129        379.0      2.9      0.0  								event_after=row["values"]
	  1065   2399703    6520071.0      2.7      1.0  							for column_name in event_after:
	  1066   2299703    6340622.0      2.8      1.0  								column_type=column_map[column_name]
	  1067   2299703    6843796.0      3.0      1.1  								if column_type in self.hexify and event_after[column_name]:
	  1068                                           									event_after[column_name]=binascii.hexlify(event_after[column_name]).decode()
	  1069   2299703    6848906.0      3.0      1.1  								elif column_type in self.hexify and isinstance(event_after[column_name], bytes):
	  1070                                           									event_after[column_name] = ''
	  1071   2397193    6480560.0      2.7      1.0  							for column_name in event_before:
	  1072   2297193    6298118.0      2.7      1.0  								column_type=column_map[column_name]
	  1073   2297193    6816384.0      3.0      1.1  								if column_type in self.hexify and event_before[column_name]:
	  1074                                           									event_before[column_name]=binascii.hexlify(event_before[column_name]).decode()
	  1075   2297193    6835182.0      3.0      1.1  								elif column_type in self.hexify and isinstance(event_before[column_name], bytes):
	  1076                                           									event_before[column_name] = ''
	  1077    100000     364835.0      3.6      0.1  							event_insert={"global_data":global_data,"event_after":event_after,  "event_before":event_before}
	  1078    100000    6829138.0     68.3      1.1  							size_insert += len(str(event_insert))
	  1079    100000     429182.0      4.3      0.1  							group_insert.append(event_insert)
	  1080                                           							
	  1081    100000     298658.0      3.0      0.0  						master_data["File"]=log_file
	  1082    100000     269740.0      2.7      0.0  						master_data["Position"]=log_position
	  1083    100000     269878.0      2.7      0.0  						master_data["Time"]=event_time
	  1084                                           						
	  1085    100000     348828.0      3.5      0.1  						if len(group_insert)>=self.replica_batch_size:
	  1086         1        372.0    372.0      0.0  							self.logger.info("Max rows per batch reached. Writing %s. rows. Size in bytes: %s " % (len(group_insert), size_insert))
	  1087         1        227.0    227.0      0.0  							self.logger.debug("Master coordinates: %s" % (master_data, ))
	  1088         1   39953572.0 39953572.0      6.4  							self.pg_engine.write_batch(group_insert)
	  1089         1          8.0      8.0      0.0  							size_insert=0
	  1090         1     482664.0 482664.0      0.1  							group_insert=[]
	  1091         1          7.0      7.0      0.0  							close_batch=True
	  1092                                           						
	  1093                                           						
	  1094                                           						
	  1095                                           		my_stream.close()
	  1096                                           		if len(group_insert)>0:
	  1097                                           			self.logger.debug("writing the last %s events" % (len(group_insert), ))
	  1098                                           			self.pg_engine.write_batch(group_insert)
	  1099                                           			close_batch=True
	  1100                                           		
	  1101                                           		return [master_data, close_batch]
	
	2018-02-11 11:51:03 read_replica DEBUG mysql_lib.py (1135): trying to save the master data...

**Comment by lingniao2000** [comment] 2018-02-11 07:32
I use the line_profiler tool for  profiling, code snippets are as follows:
                if len (batch_data)> 0:
                        id_batch = batch_data [0] [0]

                        prof = line_profiler.LineProfiler (self .__ read_replica_stream)
                        prof.enable () # Begin profiling
                        replica_data = self .__ read_replica_stream (batch_data)
                        prof.disable () # stop performance analysis
                        prof.print_stats (sys.stdout)

                        master_data = replica_data [0]
                        close_batch = replica_data [1]

**Comment by the4thdoctor** [comment] 2018-02-11 08:25
I suspect the bottleneck is caused by the method which determines if a row image should be used.
I suggest you to replace this row https://github.com/the4thdoctor/pg_chameleon/blob/master/pg_chameleon/lib/mysql_lib.py#L1024 with 

``store_row = True``

Please note that this will cause the skipped rows counter to increase again.
Nothing to worry about, no corruption in place. 

Thanks

**Comment by lingniao2000** [comment] 2018-02-11 15:06
According to your advice I test again, the problem still exists.
And from line_profiler data, this line of code time is very short. The two most time consuming statements appear pymysqlreplication reading socket data, I suspect there is a problem with the performance of the BinLogStreamReader, and the netstat command shows a high recv-Q queue, which is also a suspect basis

**Comment by the4thdoctor** [comment] 2018-02-11 16:37
well. in that case the issue the problem is with the https://github.com/noplay/python-mysql-replication library. Unfortunately is out of my control :(
I suggest to file a report with them

sorry about that

**Comment by lingniao2000** [comment] 2018-02-12 06:47
I submitted
https://github.com/noplay/python-mysql-replication/issues/251

**Comment by the4thdoctor** [comment] 2018-02-12 07:30
cool. closing this ticket then.

**Closed by the4thdoctor** 2018-02-12 07:30 UTC
Labels: question, wontfix
