### ISSUE TITLE
The data is inconsistent and the delay is too high

### ISSUE THREAD

**Issue by lingniao2000** [the4thdoctor/pg_chameleon#58] opened 2018-01-09 08:18 UTC
In recent months I have been doing pg_chameleon data synchronization test, has solved the problem of two large table import failure, such as the need to modify the mysql variable, increase the value of wait_timeout, net_write_timeout. But now there are still problems, troubleshooting for a long time can not be solved

The first is the data inconsistency, if I test a single table, and the table is not large, such as 20 million, is normal. However, if I add a large table, such as 200 million, two tables  will appear inconsistent,  about 1-20000 records lost
We added the log to read_replica_stream function: self.logger.debug ("event_insert:% s"% (event_insert)), and found that the data lost in the PG is there.
Surmised may be a problem during the replay phase

The second problem is the delay is relatively large, single cpu 100% (CPU: 88 core, MEM: 256GB)
See the attachment for troubleshooting information
Please help me, this is too painful
[pg_chameleon_debug.txt](https://github.com/the4thdoctor/pg_chameleon/files/1614350/pg_chameleon_debug.txt)

**Comment by the4thdoctor** [comment] 2018-01-09 09:48
Wow. Thanks for the report.
I'll have a look ASAP.
Which version of the tool are you using?
Many thanks

**Comment by lingniao2000** [comment] 2018-01-09 11:20
the lasted version v2.0.0 :)

Federico Campoli <notifications@github.com>于2018年1月9日 周二17:48写道：

**Comment by the4thdoctor** [comment] 2018-01-09 11:36
thanks. from what I see on your configuration you have 5 tables replicated but the limit tables is set so only 2 tables are effectively replayed. this is the reason of the skipped rows.
can you add all the tables you are replicating under the limit_tables key please?
the skipped rows probably will be always present as the rows are always read  from mysql (the mysql-replication when specifying which tables to replicate  doesn't supports the form ``schema.table`` so I cannot skip them).
Thanks

**Comment by lingniao2000** [comment] 2018-01-10 01:52
This is another strange problem, I set limit_tables in the configuration file only two tables, I do not know why there are three additional tables, and I have never been concerned about these three tables.
Yesterday, I once again made a synchronization, there is no recurrence of this problem, PG database only two tables

(chameleon) [root @ SQL-CHECK ~] # chameleon.py show_status --source prod --debug
  Source id Source name Type Status Consistent Read lag Last read Replay lag Last replay
----------- ------------- ------ -------- ------------ ---------- ------------------- ------------ --------- ----------
          1 prod mysql running Yes 08:12:04 2018-01-10 01:00:29 00:00:00 2018-01-10 01:00:29

== Schema mappings ==
Origin schema Destination schema
--------------- --------------------
db_nono db_nono

== Replica status ==
--------------------- ------
Tables not replicated 0
Tables replicated 2
All tables 2
Replayed rows 517806
Replayed DDL 0
Skipped rows 134400

**Comment by lingniao2000** [comment] 2018-01-10 02:59
Report the progress of the test yesterday
I modified fn_replay_mysql stored procedure, cancel the delete operation, observed overnight, now I do not see the missing data, I am not sure if this is the problem, or just a coincidence
[fn_replay_mysql.txt](https://github.com/the4thdoctor/pg_chameleon/files/1617366/fn_replay_mysql.txt)

**Comment by the4thdoctor** [comment] 2018-01-10 07:44
the presence of the extra tables was caused by a wrong execution of DDL when the ``tables_limit`` is set. I'm working on a fix.

For the skipped rows, they are not sign of data corruption. Disabling the delete in the replay function  will cause the log tables to bloat with performance degradation. 

As mentioned before the mysql replica stream is not filtered. Some of the logged rows are not useful for the replica (e.g. tables without primary key or not included in the replica list). 
After a batch as been replayed those extra rows are cleaned and the counter is increased.
I reckon this is not optimal for the performance and probably this is the cause of the high load cpu.
I'll find a way to filter them before writing them into the target database. 
I'll ping you when the changes are pushed.
Again, thanks for your feedback

**Comment by lingniao2000** [comment] 2018-01-10 08:18
That's great, this is really good news, thank you very much

**Comment by the4thdoctor** [comment] 2018-01-10 21:04
commit  691abd6 added the the row and ddl exclusion during the replica.
can you please test it?

**Comment by lingniao2000** [comment] 2018-01-11 23:57
very good ,i will test it today

Federico Campoli <notifications@github.com>于2018年1月11日 周四05:04写道：

**Comment by lingniao2000** [comment] 2018-01-12 07:28
Report a very good news, the data is not lost! I re-imported two tables again and synchronized, observed a few hours, the data consistent. thank you very much for your help

However, 100% CPU problems still exist, catch up to consistent state still takes a long time (more than 5 hours), and even in a consistent state, there are often a few minutes delay

**Comment by the4thdoctor** [comment] 2018-01-12 07:53
Excellent. For the reply, I need to improve it.
However I suggest to try different settings for the reply size in the configuration.
Lower values would result in faster execution. I would also increase the work mem on PostgreSQL as the reply function tends to sort on disk if the value is low.
I'm closing the ticket.
Thanks for the feedback.

**Closed by the4thdoctor** 2018-01-12 07:53 UTC
Labels: bug, v2.0, v2.1
