### ISSUE TITLE
add binlog_row_image default value 'FULL' for older mysql

### ISSUE THREAD

**Issue by flash4lekker** [the4thdoctor/pg_chameleon#70] opened 2018-04-24 10:10 UTC
Hey, 
we are using pg_chameleon v 2.0.5 and have an older mysql version 5.5.59. This version does not support mysql variable binlog_row_image, it is introduced in mysql 5.6.2.
Because of this your check_mysql_config function fails on accessing assoc array in line 59.
`/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py`
`binlog_row_image = variable_check["Value"]`

According to
[https://dev.mysql.com/doc/refman/5.6/en/replication-options-binary-log.html#sysvar_binlog_row_image](https://dev.mysql.com/doc/refman/5.6/en/replication-options-binary-log.html#sysvar_binlog_row_image)
the default value is 'FULL', also in version 5.5.59.

I replaces this line with
`if hasattr(variable_check,"Value"):`
`     binlog_row_image = variable_check["Value"]`
`else:`
`     binlog_row_image = 'FULL'`

After that init and start replica worked fine with mysql 5.5.59 - and it is still running :)
bye flash4lekker

**Comment by the4thdoctor** [comment] 2018-04-24 16:35
Hi, the issue is fixed in the upcoming release. Sorry for the delay. Hard days behind.
And thanks for the feedback :-)

**Closed** 2018-04-25 17:49 UTC
